-- MySQL Script generated by MySQL Workbench
-- Thu May 18 16:59:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema previdenciaaquidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema previdenciaaquidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `previdenciaaquidb` DEFAULT CHARACTER SET utf8 ;
USE `previdenciaaquidb` ;

-- -----------------------------------------------------
-- Table `previdenciaaquidb`.`simulacao_beneficio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `previdenciaaquidb`.`simulacao_beneficio` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `genero` ENUM('m', 'f') NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `idade` INT NULL,
  `tempo_contribuicao_mes` INT NULL,
  `idade_aposentadoria` INT NULL,
  `mes_aposentadoria` INT NULL,
  `ano_aposentadoria` INT NULL,
  `tempo_contribuicao_pendente_mes` INT NULL,
  `valor_beneficio` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `previdenciaaquidb`.`simulacao_periodo_trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `previdenciaaquidb`.`simulacao_periodo_trabalho` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mes` INT NOT NULL,
  `ano` INT NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `simulacao_beneficio_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_simulacao_periodo_trabalho_simulacao_beneficio_idx` (`simulacao_beneficio_id` ASC),
  CONSTRAINT `fk_simulacao_periodo_trabalho_simulacao_beneficio`
    FOREIGN KEY (`simulacao_beneficio_id`)
    REFERENCES `previdenciaaquidb`.`simulacao_beneficio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
